In [389]:
import numpy as np
from random import randint
import networkx as nx
import matplotlib.pyplot as plt
import random
MIN_X = -100
MIN_Y = -100
MIN_Z = 0
MAX_X = 100
MAX_Y = 100
MAX_Z = 50
NUMBER_OF_CONNECTIONS = 2
NUMBER_OF_CITIES = 4


class City:
    def __init__(self) -> None:
        self.cords = np.array([
            randint(MIN_X, MAX_X),
            randint(MIN_Y, MAX_Y),
            randint(MIN_Z, MAX_Z)
        ])
        self.distances = []


class WebOfCities:
    def __init__(self, number_of_cities) -> None:
        self.number_of_cities = number_of_cities
        self.cities = []
        self.create_list_of_cities()

    def create_list_of_cities(self):
        self.cities = [City() for _ in range(0, self.number_of_cities)]

    def create_weighted_connections_100(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*0.9)
                elif city.cords[2]  < self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*1.1)
                else:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
            city.distances = distance

    def create_weighted_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*0.9
                elif city.cords[2]  < self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*1.1
                else:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)
                if random.random() > 0.2:
                    distance.append(actual_distance)
                else:
                    distance.append(0)
            city.distances = distance

    def create_connections_100(self):
        for city in self.cities:
            distance = [np.linalg.norm(city.cords - self.cities[i].cords) for i in range(0, len(self.cities))]
            city.distances = distance
    
    def create_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if random.random() > 0.2:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
                else:
                    distance.append(0)
            city.distances = distance

class Graph:
    def __init__(self, cities) -> None:
        self.cities = cities

    def create_adjacency_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix

    def create_adjacency_weighted_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix


In [390]:
class PathCounter:
    def __init__(self, adjacency_matrix, all_paths) -> None:
        self.adjacency_matrix = adjacency_matrix
        self.all_paths = all_paths
        self.all_distances = []
        self.index_of_min_distance = 0

    def count_all_distances(self):
        for path in self.all_paths:
            distance = 0
            for i in range(len(path)-1):
                distance += self.adjacency_matrix[path[i]][path[i+1]]
                # if self.adjacency_matrix[path[i]][path[i+1]] == 0:
                #    print("error")
            self.all_distances.append(distance)

    def print_min_possible_path(self):
        min_distance = min(self.all_distances)
        self.index_of_min_distance = self.all_distances.index(min_distance)
        print(f"min distance is {min_distance} for path")
        print(self.all_paths[self.index_of_min_distance])
            


In [391]:
class BranchAlgorytm:
    def __init__(self, graph, start) -> None:
        self.graph = graph
        self.start = start

    def tsp_dfs(self):
        all_paths = []
        num_cities = len(self.graph)
        stack = [[self.start]]  # Stack to keep track of current path

        while stack:
            path = stack.pop(0)  # Pop the current path from stack
            curr_city = path[-1]  # Get the current city

            if len(path) == num_cities:  # If all cities visited
                last_city = path[-1]
                if self.graph[last_city][0] != 0:
                    path.append(0)
                    all_paths.append(path)
                    #print(path)
                continue

            # Explore all unvisited neighbors of current city
            for next_city in range(num_cities):
                if next_city not in path and self.graph[curr_city][next_city] != 0:
                    stack.append(path + [next_city])  # Push updated path onto stack
                    #print(stack)

        return all_paths
    
    def tsp_bfs(self):
        all_paths = []
        num_cities = len(self.graph)
        stack = [[self.start]]  # Stack to keep track of current path

        while stack:
            path = stack.pop()  # Pop the current path from stack
            curr_city = path[-1]  # Get the current city

            if len(path) == num_cities:  # If all cities visited
                last_city = path[-1]
                if self.graph[last_city][0] != 0:
                    path.append(0)
                    all_paths.append(path)
                    #print(path)
                continue

            # Explore all unvisited neighbors of current city
            for next_city in range(num_cities):
                if next_city not in path and self.graph[curr_city][next_city] != 0:
                    stack.append(path + [next_city])  # Push updated path onto stack
                    #print(stack)

        return all_paths
    

In [392]:
START_CITY = 0


web = WebOfCities(5)
graph = Graph(web.cities)
web.create_connections_100()
adjacency_matrix = graph.create_adjacency_matrix()
print(adjacency_matrix)



[[  0.          69.70652767  62.72160712  60.9672043   90.42676595]
 [ 69.70652767   0.          27.58622845 104.6995702  125.35549449]
 [ 62.72160712  27.58622845   0.         102.43534546 131.82943526]
 [ 60.9672043  104.6995702  102.43534546   0.          44.74371464]
 [ 90.42676595 125.35549449 131.82943526  44.74371464   0.        ]]


In [393]:

branch_algorytms = BranchAlgorytm(adjacency_matrix, START_CITY)
all_paths = branch_algorytms.tsp_dfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)
all_paths = branch_algorytms.tsp_bfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)


min distance is 321.37424900629037 for path
[0, 2, 1, 4, 3, 0]
min distance is 321.37424900629037 for path
[0, 3, 4, 1, 2, 0]


In [394]:
START_CITY = 0


web = WebOfCities(5)
graph = Graph(web.cities)
web.create_connections_80()
adjacency_matrix = graph.create_adjacency_matrix()
print(adjacency_matrix)

[[  0.          13.60147051  16.64331698 190.2472076  170.9210344 ]
 [  0.           0.          29.15475947 187.64061394 175.63883397]
 [ 16.64331698  29.15475947   0.         185.81980519 160.01562424]
 [190.2472076  187.64061394 185.81980519   0.         128.5301521 ]
 [170.9210344  175.63883397 160.01562424 128.5301521    0.        ]]


In [395]:
branch_algorytms = BranchAlgorytm(adjacency_matrix, START_CITY)
all_paths = branch_algorytms.tsp_dfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)
all_paths = branch_algorytms.tsp_bfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)



min distance is 506.4311777680267 for path
[0, 1, 3, 4, 2, 0]
min distance is 506.4311777680267 for path
[0, 1, 3, 4, 2, 0]


In [396]:
START_CITY = 0


web = WebOfCities(5)
graph = Graph(web.cities)
web.create_weighted_connections_100()
adjacency_matrix = graph.create_adjacency_weighted_matrix()
print(adjacency_matrix)



[[  0.         109.30091491  88.281425    76.85056929  95.6747093 ]
 [133.59000711   0.         199.00577881 109.48177931 178.40358741]
 [ 72.23025682 162.82290994   0.          98.09138596  44.79040076]
 [ 62.87773851  89.57600125  80.25658851   0.          69.44825412]
 [ 78.27930761 145.96657152  36.64669153  56.82129882   0.        ]]


In [397]:
branch_algorytms = BranchAlgorytm(adjacency_matrix, START_CITY)
all_paths = branch_algorytms.tsp_dfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)
all_paths = branch_algorytms.tsp_bfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)


min distance is 397.10789667968726 for path
[0, 1, 3, 4, 2, 0]
min distance is 397.10789667968726 for path
[0, 1, 3, 4, 2, 0]


In [398]:
START_CITY = 0


web = WebOfCities(5)
graph = Graph(web.cities)
web.create_weighted_connections_80()
adjacency_matrix = graph.create_adjacency_weighted_matrix()
print(adjacency_matrix)



[[  0.         169.58971077 101.9267384  122.0852571  143.12546943]
 [  0.           0.         176.68675672 159.59718043 193.37799771]
 [124.57712471 215.95048043   0.          41.87230588   0.        ]
 [149.21531423 195.06322052  34.25915936   0.           0.        ]
 [174.93112931   0.          70.60269117  41.23336028   0.        ]]


In [399]:
branch_algorytms = BranchAlgorytm(adjacency_matrix, START_CITY)
all_paths = branch_algorytms.tsp_dfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)
all_paths = branch_algorytms.tsp_bfs()
path_counter = PathCounter(adjacency_matrix, all_paths)
path_counter.count_all_distances()
path_counter.print_min_possible_path()
# print(path_counter.all_paths)
# print(path_counter.all_distances)
# print(path_counter.index_of_min_distance)

min distance is 563.0373528325109 for path
[0, 1, 4, 3, 2, 0]
min distance is 563.0373528325109 for path
[0, 1, 4, 3, 2, 0]
