In [1444]:
import numpy as np
from random import randint
#import networkx as nx
import matplotlib.pyplot as plt
import random
MIN_X = -100
MIN_Y = -100
MIN_Z = 0
MAX_X = 100
MAX_Y = 100
MAX_Z = 50
NUMBER_OF_CONNECTIONS = 2
NUMBER_OF_CITIES = 4


class City:
    def __init__(self) -> None:
        self.cords = np.array([
            randint(MIN_X, MAX_X),
            randint(MIN_Y, MAX_Y),
            randint(MIN_Z, MAX_Z)
        ])
        self.distances = []


class WebOfCities:
    def __init__(self, number_of_cities) -> None:
        self.number_of_cities = number_of_cities
        self.cities = []
        self.create_list_of_cities()

    def create_list_of_cities(self):
        self.cities = [City() for _ in range(0, self.number_of_cities)]

    def create_weighted_connections_100(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*0.9)
                elif city.cords[2]  < self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*1.1)
                else:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
            city.distances = distance

    def create_weighted_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*0.9
                elif city.cords[2]  < self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*1.1
                else:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)
                if random.random() > 0.2:
                    distance.append(actual_distance)
                else:
                    distance.append(0)
            city.distances = distance

    def create_connections_100(self):
        for city in self.cities:
            distance = [np.linalg.norm(city.cords - self.cities[i].cords) for i in range(0, len(self.cities))]
            city.distances = distance
    
    def create_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if random.random() > 0.2:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
                else:
                    distance.append(0)
            city.distances = distance

class Graph:
    def __init__(self, cities) -> None:
        self.cities = cities

    def create_adjacency_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix

    def create_adjacency_weighted_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix


In [1445]:
class PathCounter:
    def __init__(self, adjacency_matrix, all_paths) -> None:
        self.adjacency_matrix = adjacency_matrix
        self.all_paths = all_paths
        self.all_distances = []
        self.index_of_min_distance = 0

    def count_all_distances(self):
        for path in self.all_paths:
            distance = 0
            for i in range(len(path)-1):
                distance += self.adjacency_matrix[path[i]][path[i+1]]
                # if self.adjacency_matrix[path[i]][path[i+1]] == 0:
                #    print("error")
            self.all_distances.append(distance)

    def print_min_possible_path(self):
        min_distance = min(self.all_distances)
        self.index_of_min_distance = self.all_distances.index(min_distance)
        print(f"min distance is {min_distance} for path")
        print(self.all_paths[self.index_of_min_distance])

In [1446]:
START_CITY = 0

web = WebOfCities(10)
graph = Graph(web.cities)
web.create_connections_80()
adjacency_matrix = graph.create_adjacency_matrix()
print(adjacency_matrix)

# adjacency_matrix = np.array([[  0.0, 81.2034482, 144.29830214, 112.44554237,  68.80406965],
#  [81.2034482,    0.0,         213.52751579, 179.22611417,  99.58915604],
#  [144.29830214, 213.52751579,   0.0,          39.2173431,  127.89839718],
#  [112.44554237, 179.22611417,   0.0,           0.0,         101.41991915],
#  [ 68.80406965,  99.58915604, 127.89839718, 101.41991915,   0.0        ]])

# print(adjacency_matrix)


# copy_adjacency_matrix = np.array([[  0.0,         190.37857022,  60.8358447,  205.27298897, 157.130519  ],
#  [190.37857022,   0.0,         132.03408651,  44.77722635,  66.76825593],
#  [ 60.8358447,  132.03408651,   0.0,         144.58907289,  96.95875412],
#  [205.27298897,   0.0,         144.58907289,   0.0,          57.22761571],
#  [157.130519,    66.76825593,  96.95875412,  57.22761571,   0.0        ]])

# adjacency_matrix = np.array([[  0.0,         190.37857022,  60.8358447,  205.27298897, 157.130519  ],
#  [190.37857022,   0.0,         132.03408651,  44.77722635,  66.76825593],
#  [ 60.8358447,  132.03408651,   0.0,         144.58907289,  96.95875412],
#  [205.27298897,   0.0,         144.58907289,   0.0,          57.22761571],
#  [157.130519,    66.76825593,  96.95875412,  57.22761571,   0.0        ]]) 



# [[  0.0           0.0          77.64663547  72.31182476   0.0        ]
#  [ 68.65129278   0.0         106.54576481 117.58401252  61.17188897]
#  [ 77.64663547 106.54576481   0.0          27.74887385  48.80573737]
#  [ 72.31182476 117.58401252  27.74887385   0.0           0.0        ]
#  [ 62.71363488   0.0           0.0          67.73477689   0.0        ]]

# [[  0.           0.         129.27876856  56.16938668 162.39766008] 1
#  [100.41912169   0.           0.           0.           0.        ]
#  [  0.         144.39182802   0.          93.13431162  34.43835072]
#  [ 56.16938668 131.7383771   93.13431162   0.         125.03599482]
#  [162.39766008   0.          34.43835072 125.03599482   0.        ]]

# [[  0.          67.38694236  42.07136794  69.26759704 105.89145386]
#  [ 67.38694236   0.          56.43580424  41.24318125 141.03191128]
#  [ 42.07136794   0.           0.          72.26340706 144.73078456]
#  [ 69.26759704   0.          72.26340706   0.           0.        ]
#  [  0.         141.03191128 144.73078456 115.15641537   0.        ]]

# adjacency_matrix = np.array([[  0.0,           0.0,         102.00980345,   0.0,         101.84792585],
#  [ 97.34988444,   0.0,          17.80449381,  25.51470164, 163.07666909],
#  [102.00980345,   0.0,           0.0,          30.03331484,   0.0        ],
#  [ 88.14760348,   0.0,          30.03331484,   0.0,         140.63072211],
#  [101.84792585, 163.07666909, 165.93070843, 140.63072211,   0.0        ]])
# print(adjacency_matrix)


[[  0.         154.12008305  93.79765455  93.77632964 112.33877336
  102.49878048  79.36623967   0.         135.78291498 126.83847997]
 [154.12008305   0.         151.42324788 107.83784122  81.78630692
  104.66613588 223.48601746  84.1011296  170.85081211 185.02162036]
 [ 93.79765455 151.42324788   0.          48.74423043  73.71566998
    0.         105.55093557   0.           0.           0.        ]
 [ 93.77632964 107.83784122  48.74423043   0.          29.49576241
  118.60016863   0.          99.55902772  87.6184912   82.30431337]
 [112.33877336   0.          73.71566998  29.49576241   0.
  115.99137899 162.83427158  94.49867724 100.42410069 104.93807698]
 [102.49878048 104.66613588 155.06772714 118.60016863 115.99137899
    0.         179.59120246  31.84336666 197.89138435 192.69146323]
 [ 79.36623967 223.48601746 105.55093557 136.41480858 162.83427158
  179.59120246   0.           0.         135.3144486  115.90944741]
 [ 90.09994451  84.1011296  135.58761005  99.55902772  94.49867

In [1447]:
def sort_by_indexes(lst, indexes, reverse=False):
  return [val for (_, val) in sorted(zip(indexes, lst), key=lambda x: \
          x[0], reverse=reverse)]

class AlgorytmManager():
    def __init__(self, start_city, adjacency_matrix) -> None:
        self.start_city = start_city
        self.adjacency_matrix = adjacency_matrix
        self.copy_adjacency_matrix = np.copy(adjacency_matrix)

    def NN_algorytm(self):
        current_city = self.start_city
        visited_cities = [self.start_city]
        max_distance_in_matrix = self.adjacency_matrix.max() + 1
        while len(visited_cities) != len(self.adjacency_matrix):
            dist_from_cur_cit = self.adjacency_matrix[current_city,:]
            dist_from_cur_cit = np.ma.masked_equal(dist_from_cur_cit, 0.0, copy=False)
            min_dis_from_cur_cit = dist_from_cur_cit.min()
            index_of_nearest_city = np.where(dist_from_cur_cit == min_dis_from_cur_cit)
            #print(index_of_nearest_city)
            index_of_nearest_city = index_of_nearest_city[0][0]
            if not index_of_nearest_city in visited_cities:
                visited_cities.append(index_of_nearest_city)
                current_city = index_of_nearest_city
                #print(index_of_nearest_city)
            else:
                self.adjacency_matrix[current_city][index_of_nearest_city] = max_distance_in_matrix
            dist_from_cur_cit = self.adjacency_matrix[current_city,:]
            dead_end = (dist_from_cur_cit == max_distance_in_matrix) | (dist_from_cur_cit == 0)
            if dead_end.all():
                print("no path")
                return
        last_visited_city = visited_cities[-1]
        if self.adjacency_matrix[last_visited_city][0] != 0:
            visited_cities.append(0)
        else:
            print("connection with 0 doesn't exist")
            return
        print(visited_cities)

    def NN_algorytm_V2(self):
        visited_cities = [self.start_city]
        current_city = self.start_city
        max_distance_in_matrix = self.adjacency_matrix.max() + 1
        #seckond_dead_end = False
        dead_ends_list = []
        while len(visited_cities) != len(self.adjacency_matrix):
            dist_from_cur_cit = self.adjacency_matrix[current_city,:]
            dist_from_cur_cit = np.ma.masked_equal(dist_from_cur_cit, 0.0, copy=False)
            min_dis_from_cur_cit = dist_from_cur_cit.min()
            index_of_nearest_city= np.where(dist_from_cur_cit == min_dis_from_cur_cit)
            index_of_nearest_city = index_of_nearest_city[0][0]
            if not index_of_nearest_city in visited_cities:
                visited_cities.append(index_of_nearest_city)
                current_city = index_of_nearest_city
            else:
                self.adjacency_matrix[current_city][index_of_nearest_city] = max_distance_in_matrix
            dist_from_cur_cit = self.adjacency_matrix[current_city,:]
            dead_end = (dist_from_cur_cit == max_distance_in_matrix) | (dist_from_cur_cit == 0)
            if dead_end.all():
                dead_end_city = visited_cities.pop()
                dead_ends_list.append(dead_end_city)
                dead_ends_list = list(set(dead_ends_list))
                dist_from_cur_cit = self.adjacency_matrix[visited_cities[-1],:]
                for city in visited_cities:
                    dist_from_cur_cit[city] = max_distance_in_matrix
                arr_filtered = dist_from_cur_cit[(dist_from_cur_cit != 0) | (dist_from_cur_cit == max_distance_in_matrix)]
                second_smallest = np.partition(arr_filtered, 1)[1]
                index_of_nearest_city= np.where(dist_from_cur_cit == second_smallest)
                current_city = index_of_nearest_city[0][0]
                self.adjacency_matrix = np.copy(self.copy_adjacency_matrix)
                visited_cities.append(current_city)
                if len(dead_ends_list) > 1 or second_smallest == max_distance_in_matrix:
                    print("seckond dead_end")
                    return
                #seckond_dead_end = True
        last_visited_city = visited_cities[-1] 
        if self.adjacency_matrix[last_visited_city][0] != 0:
            visited_cities.append(0)
        else:
            print("connection with 0 doesn't exist")
            return
        print(visited_cities)
        
algorytm_manager_1 = AlgorytmManager(0, adjacency_matrix=adjacency_matrix)
algorytm_manager_1.NN_algorytm()
algorytm_manager_2 = AlgorytmManager(0, adjacency_matrix=adjacency_matrix)
algorytm_manager_2.NN_algorytm_V2()


[0, 6, 2, 3, 4, 7, 1, 5, 9, 8, 0]
[0, 6, 2, 3, 4, 7, 1, 5, 9, 8, 0]
