In [39]:
import numpy as np
from random import randint
from heapq import nsmallest
import networkx as nx
import matplotlib.pyplot as plt
MIN_X = -100
MIN_Y = -100
MIN_Z = 0
MAX_X = 100
MAX_Y = 100
MAX_Z = 50
NUMBER_OF_CONNECTIONS = 2


class City:
    def __init__(self) -> None:
        self.cords = np.array([
            randint(MIN_X, MAX_X),
            randint(MIN_Y, MAX_Y),
            randint(MIN_Z, MAX_Z)
        ])
        self.connections = []


class WebOfCities:
    def __init__(self, number_of_cities) -> None:
        self.number_of_cities = number_of_cities
        self.cities = []
        self.create_list_of_cities()

    def create_list_of_cities(self):
        self.cities = [City() for _ in range(0, self.number_of_cities)]

    def create_connections(self):
        for city in self.cities:
            distance = [np.linalg.norm(city.cords - self.cities[i].cords) for i in range(0, len(self.cities))]
            #print(distance)
            smalest_values = nsmallest(NUMBER_OF_CONNECTIONS + 1, distance)
            nearest_cities = [distance.index(value) for value in smalest_values[1:]]
            city.connections = nearest_cities

class Graph:
    def __init__(self, cities) -> None:
        self.cities = cities

    def create_adjacency_matrix(self):
        print(np.zeros((len(self.cities), (len(self.cities)))))
            

            




In [40]:
web = WebOfCities(7)
cords = [city.cords for city in web.cities]
print(cords)
web.create_connections()
# for i in range(len(web.cities)):
#     print(web.cities[i].connections)
graph = Graph(web.cities)
graph.create_adjacency_matrix()



    

[array([-24,  37,  44]), array([ 51, -47,  42]), array([90, 37, 40]), array([-68,  22,   6]), array([-82, -65,  40]), array([-31, -46,  37]), array([13,  7, 44])]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
def createAdjacencyMatrix(vertices,edges):
  noofvertices=len(vertices)
  adjM=[]
  while(len(adjM)<noofvertices):
    temp=[]
    for i in range(noofvertices):
      temp.append(0)
    adjM.append(temp)
  for edge in edges:
    i=edge[0]
    j=edge[1]
    if i>=noofvertices or j>=noofvertices or i<0 or j<0:
      print(f"Not a Proper Input in Edge {i},{j}")
    else:
      adjM[i][j]=1
      adjM[j][i]=1
  G=nx.Graph()
  G.add_edges_from(edges)
  nx.draw_networkx(G)
  plt.show()
  return adjM

vertices=[0,1,2,3,4,5]
edges=[[1,4],[5,4],[0,5],[3,5],[4,5],[1,3],[0,3],[0,2],[5,3],[5,1]]

createAdjacencyMatrix(vertices, edges)