In [31]:
import numpy as np
from random import randint
import networkx as nx
import matplotlib.pyplot as plt
import random
MIN_X = -100
MIN_Y = -100
MIN_Z = 0
MAX_X = 100
MAX_Y = 100
MAX_Z = 50
NUMBER_OF_CONNECTIONS = 2
NUMBER_OF_CITIES = 4


class City:
    def __init__(self) -> None:
        self.cords = np.array([
            randint(MIN_X, MAX_X),
            randint(MIN_Y, MAX_Y),
            randint(MIN_Z, MAX_Z)
        ])
        self.distances = []


class WebOfCities:
    def __init__(self, number_of_cities) -> None:
        self.number_of_cities = number_of_cities
        self.cities = []
        self.create_list_of_cities()

    def create_list_of_cities(self):
        self.cities = [City() for _ in range(0, self.number_of_cities)]

    def create_weighted_connections_100(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*0.9)
                elif city.cords[2]  < self.cities[i].cords[2]:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords)*1.1)
                else:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
            city.distances = distance

    def create_weighted_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if city.cords[2]  > self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*0.9
                elif city.cords[2]  < self.cities[i].cords[2]:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)*1.1
                else:
                    actual_distance = np.linalg.norm(city.cords - self.cities[i].cords)
                if random.random() > 0.2:
                    distance.append(actual_distance)
                else:
                    distance.append(0)
            city.distances = distance

    def create_connections_100(self):
        for city in self.cities:
            distance = [np.linalg.norm(city.cords - self.cities[i].cords) for i in range(0, len(self.cities))]
            city.distances = distance
    
    def create_connections_80(self):
        for city in self.cities:
            distance = []
            for i in range(0, self.number_of_cities):
                if random.random() > 0.2:
                    distance.append(np.linalg.norm(city.cords - self.cities[i].cords))
                else:
                    distance.append(0)
            city.distances = distance

class Graph:
    def __init__(self, cities) -> None:
        self.cities = cities

    def create_adjacency_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix

    def create_adjacency_weighted_matrix(self):
        adjacency_matrix_ls = []
        for city in self.cities:
            list_of_distance = []
            for distance in city.distances:
                list_of_distance.append(distance)
            adjacency_matrix_ls.append(list_of_distance)
        adjacency_matrix = np.array(adjacency_matrix_ls)
        return adjacency_matrix


In [185]:
class PathCounter:
    def __init__(self, adjacency_matrix, all_paths) -> None:
        self.adjacency_matrix = adjacency_matrix
        self.all_paths = all_paths
        self.all_distances = []
        self.index_of_min_distance = 0

    def count_all_distances(self):
        for path in self.all_paths:
            distance = 0
            for i in range(len(path)-1):
                distance += self.adjacency_matrix[path[i]][path[i+1]]
                # if self.adjacency_matrix[path[i]][path[i+1]] == 0:
                #    print("error")
            self.all_distances.append(distance)

    def print_min_possible_path(self):
        min_distance = min(self.all_distances)
        self.index_of_min_distance = self.all_distances.index(min_distance)
        print(f"min distance is {min_distance} for path")
        print(self.all_paths[self.index_of_min_distance])

In [190]:
START_CITY = 0

web = WebOfCities(5)
graph = Graph(web.cities)
web.create_connections_80()
adjacency_matrix = graph.create_adjacency_matrix()
print(adjacency_matrix)

# adjacency_matrix = np.array([[  0.0, 81.2034482, 144.29830214, 112.44554237,  68.80406965],
#  [81.2034482,    0.0,         213.52751579, 179.22611417,  99.58915604],
#  [144.29830214, 213.52751579,   0.0,          39.2173431,  127.89839718],
#  [112.44554237, 179.22611417,   0.0,           0.0,         101.41991915],
#  [ 68.80406965,  99.58915604, 127.89839718, 101.41991915,   0.0        ]])

# copy_adjacency_matrix = np.array([[  0.0,         190.37857022,  60.8358447,  205.27298897, 157.130519  ],
#  [190.37857022,   0.0,         132.03408651,  44.77722635,  66.76825593],
#  [ 60.8358447,  132.03408651,   0.0,         144.58907289,  96.95875412],
#  [205.27298897,   0.0,         144.58907289,   0.0,          57.22761571],
#  [157.130519,    66.76825593,  96.95875412,  57.22761571,   0.0        ]])

# adjacency_matrix = np.array([[  0.0,         190.37857022,  60.8358447,  205.27298897, 157.130519  ],
#  [190.37857022,   0.0,         132.03408651,  44.77722635,  66.76825593],
#  [ 60.8358447,  132.03408651,   0.0,         144.58907289,  96.95875412],
#  [205.27298897,   0.0,         144.58907289,   0.0,          57.22761571],
#  [157.130519,    66.76825593,  96.95875412,  57.22761571,   0.0        ]])

[[  0.          25.15949125  94.9578854   71.65193647 138.51353724]
 [ 25.15949125   0.           0.          83.95832299 157.01273834]
 [ 94.9578854    0.           0.          35.59494346  80.36790404]
 [ 71.65193647   0.          35.59494346   0.          77.89736838]
 [138.51353724 157.01273834  80.36790404   0.           0.        ]]


In [191]:
def sort_by_indexes(lst, indexes, reverse=False):
  return [val for (_, val) in sorted(zip(indexes, lst), key=lambda x: \
          x[0], reverse=reverse)]

class AlgorytmManager():
    def __init__(self, start_city, adjacency_matrix) -> None:
        self.start_city = start_city
        self.adjacency_matrix = adjacency_matrix
        self.copy_adjacency_matrix = adjacency_matrix

    def NN_algorytm(self):
        visited_cities = [self.start_city]
        next_city = self.start_city
        max_distance_in_matrix = adjacency_matrix.max()
        while len(visited_cities) != len(adjacency_matrix):
            dist_from_cur_cit = adjacency_matrix[next_city,:]
            dist_from_cur_cit = np.ma.masked_equal(dist_from_cur_cit, 0.0, copy=False)
            min_dis_from_cur_cit = dist_from_cur_cit.min()
            index_of_nearest_city= np.where(dist_from_cur_cit == min_dis_from_cur_cit)
            #print(index_of_nearest_city)
            index_of_nearest_city = index_of_nearest_city[0][0]
            if not index_of_nearest_city in visited_cities:
                visited_cities.append(index_of_nearest_city)
                next_city = index_of_nearest_city
                #print(index_of_nearest_city)
            else:
                adjacency_matrix[next_city][index_of_nearest_city] = max_distance_in_matrix + 1 #żeby funkcja min mogła zadziałać
            dist_from_cur_cit = adjacency_matrix[next_city,:]
            dead_end = (dist_from_cur_cit == max_distance_in_matrix + 1) | (dist_from_cur_cit == 0)
            if dead_end.all():
                print("no path")
                return
        
        last_visited_city = visited_cities[-1]
        if adjacency_matrix[last_visited_city][0] != 0:
            visited_cities.append(0)
        else:
            print("connection with 0 doesn't exist")
        print(visited_cities)

    def NN_algorytm_V2(self):
        visited_cities = [self.start_city]
        next_city = self.start_city
        max_distance_in_matrix = self.adjacency_matrix.max()
        while len(visited_cities) != len(adjacency_matrix):
            dist_from_cur_cit = adjacency_matrix[next_city,:]
            dist_from_cur_cit = np.ma.masked_equal(dist_from_cur_cit, 0.0, copy=False)
            min_dis_from_cur_cit = dist_from_cur_cit.min()
            index_of_nearest_city= np.where(dist_from_cur_cit == min_dis_from_cur_cit)
            #print(index_of_nearest_city)
            index_of_nearest_city = index_of_nearest_city[0][0]
            if not index_of_nearest_city in visited_cities:
                visited_cities.append(index_of_nearest_city)
                next_city = index_of_nearest_city
                #print(index_of_nearest_city)
            else:
                adjacency_matrix[next_city][index_of_nearest_city] = max_distance_in_matrix + 1 #żeby funkcja min mogła zadziałać
            dist_from_cur_cit = adjacency_matrix[next_city,:]
            dead_end = (dist_from_cur_cit == max_distance_in_matrix + 1) | (dist_from_cur_cit == 0)
            if dead_end.all():
                visited_cities.pop()
                #print(adjacency_matrix)
                dist_from_cur_cit = adjacency_matrix[visited_cities[-1],:]
                arr_filtered = dist_from_cur_cit[dist_from_cur_cit != 0]
                second_smallest = np.partition(arr_filtered, 1)[1]
                index_of_nearest_city= np.where(dist_from_cur_cit == second_smallest)
                next_city = index_of_nearest_city[0][0]
                adjacency_matrix = np.copy(self.copy_adjacency_matrix)
                #adjacency_matrix[next_city][bad_end_city] = max_distance_in_matrix + 1
                visited_cities.append(next_city)
                print(next_city)
        last_visited_city = visited_cities[-1] 
        if adjacency_matrix[last_visited_city][0] != 0:
            visited_cities.append(0)
        else:
            print("connection with 0 doesn't exist")
        print(visited_cities)



algorytm_manager = AlgorytmManager(0, adjacency_matrix=adjacency_matrix)
algorytm_manager.NN_algorytm()
algorytm_manager.NN_algorytm_V2()

[0, 1, 3, 2, 4, 0]


UnboundLocalError: cannot access local variable 'adjacency_matrix' where it is not associated with a value